-- Sample data insert statements parsed from cocktails_data.csv
-- Note: Ingredient categories, subcategories, and ABV are NULL - update manually if needed
-- Note: Flavor profiles are not included - add separately if needed

-- Insert ingredients first (these will be referenced by drinks)
-- Note: Category, subcategory, and ABV are NULL - you may want to update these manually
INSERT INTO ingredients (name, category, subcategory, abv) VALUES
('100% Agave Tequila', NULL, NULL, NULL),
('2-3 Quarter Size Sliced Fresh Ginger', NULL, NULL, NULL),
('Absinthe', NULL, NULL, NULL),
('Agave Nectar', NULL, NULL, NULL),
('Aged Rum', NULL, NULL, NULL),
('Allspice Saint Elizabeth15 Ml Fresh Lime Juice', NULL, NULL, NULL),
('Amaretto', NULL, NULL, NULL),
('Amaro Nonino', NULL, NULL, NULL),
('Amber Jamaican Rum', NULL, NULL, NULL),
('Amontillado Sherry', NULL, NULL, NULL),
('Angostura', NULL, NULL, NULL),
('Angostura Bitters', NULL, NULL, NULL),
('Aperol', NULL, NULL, NULL),
('Apricot Brandy', NULL, NULL, NULL),
('Aromatic Bitters', NULL, NULL, NULL),
('Bénédictine', NULL, NULL, NULL),
('Bitter Campari', NULL, NULL, NULL),
('Blackstrap Rum', NULL, NULL, NULL),
('Blended Aged Rum', NULL, NULL, NULL),
('Blended Scotch Whisky', NULL, NULL, NULL),
('Bourbon Whiskey', NULL, NULL, NULL),
('Bourbon or Rye Whiskey', NULL, NULL, NULL),
('Brandy', NULL, NULL, NULL),
('Brut Champagne or Prosecco', NULL, NULL, NULL),
('Cachaca', NULL, NULL, NULL),
('Cachaça', NULL, NULL, NULL),
('Calvados', NULL, NULL, NULL),
('Campari', NULL, NULL, NULL),
('Chamomile Cordial', NULL, NULL, NULL),
('Champagne', NULL, NULL, NULL),
('Cherry Brandy Luxardo', NULL, NULL, NULL),
('Cherry Sangue Morlacco', NULL, NULL, NULL),
('Chilled Champagne', NULL, NULL, NULL),
('Cloves', NULL, NULL, NULL),
('Coconut Cream', NULL, NULL, NULL),
('Coffee Liqueur', NULL, NULL, NULL),
('Cognac', NULL, NULL, NULL),
('Cognac or Brandy', NULL, NULL, NULL),
('Cointreau', NULL, NULL, NULL),
('Cola', NULL, NULL, NULL),
('Cranberry Juice', NULL, NULL, NULL),
('Cream', NULL, NULL, NULL),
('Creme de Cassis', NULL, NULL, NULL),
('Crème de Cassis', NULL, NULL, NULL),
('Crème de Cacao', NULL, NULL, NULL),
('Crème de Menthe', NULL, NULL, NULL),
('Crème de Mûre', NULL, NULL, NULL),
('Crème de Violette', NULL, NULL, NULL),
('Cuban Aguardiente', NULL, NULL, NULL),
('Cuban Rum', NULL, NULL, NULL),
('Curacao', NULL, NULL, NULL),
('Cynar', NULL, NULL, NULL),
('DOM Bénédictine', NULL, NULL, NULL),
('Dash Absinthe', NULL, NULL, NULL),
('Dash Angostura Bitters', NULL, NULL, NULL),
('Dash of Angostura Bitters', NULL, NULL, NULL),
('Demerara Rum', NULL, NULL, NULL),
('Demerara Sugar Syrup', NULL, NULL, NULL),
('Donn’s Mix*', NULL, NULL, NULL),
('Drambuie', NULL, NULL, NULL),
('Dry Gin', NULL, NULL, NULL),
('Dry Vermouth', NULL, NULL, NULL),
('Dry White Wine', NULL, NULL, NULL),
('Egg White', NULL, NULL, NULL),
('Egg Yolk', NULL, NULL, NULL),
('Elderflower Cordial', NULL, NULL, NULL),
('Espadin Mezcal', NULL, NULL, NULL),
('Falernum', NULL, NULL, NULL),
('Fernet', NULL, NULL, NULL),
('Fernet Branca', NULL, NULL, NULL),
('Fresh Cream', NULL, NULL, NULL),
('Fresh Lemon Juice', NULL, NULL, NULL),
('Fresh Lime', NULL, NULL, NULL),
('Fresh Lime Juice', NULL, NULL, NULL),
('Fresh Mint Sprigs', NULL, NULL, NULL),
('Fresh Orange Juice', NULL, NULL, NULL),
('Fresh Pineapple Juice', NULL, NULL, NULL),
('Fresh Squeezed Lemon Juice', NULL, NULL, NULL),
('Fresh Squeezed Lime Juice', NULL, NULL, NULL),
('Freshly Squeezed Lemon Juice', NULL, NULL, NULL),
('Freshly Squeezed Lime Juice', NULL, NULL, NULL),
('Freshly Squeezed Orange Juice', NULL, NULL, NULL),
('Gengibre Slice', NULL, NULL, NULL),
('Gin', NULL, NULL, NULL),
('Ginger Ale', NULL, NULL, NULL),
('Ginger Beer', NULL, NULL, NULL),
('Gold Jamaican Rum', NULL, NULL, NULL),
('Gold Puerto Rican Rum', NULL, NULL, NULL),
('Goslings Rum', NULL, NULL, NULL),
('Grand Marnier', NULL, NULL, NULL),
('Grapefruit Juice', NULL, NULL, NULL),
('Green Chartreuse', NULL, NULL, NULL),
('Grenadine Syrup', NULL, NULL, NULL),
('Honey Mix', NULL, NULL, NULL),
('Honey Mix (replace Water With Chamomile)*', NULL, NULL, NULL),
('Honey Syrup', NULL, NULL, NULL),
('Hot Coffee', NULL, NULL, NULL),
('Irish Whiskey', NULL, NULL, NULL),
('Italian Basil Leaves', NULL, NULL, NULL),
('Jamaica Overproof White Rum', NULL, NULL, NULL),
('Jamaican Dark Rum', NULL, NULL, NULL),
('Jamaican Rum', NULL, NULL, NULL),
('Kahlúa', NULL, NULL, NULL),
('Lagavulin 16y', NULL, NULL, NULL),
('Lemon Juice', NULL, NULL, NULL),
('Lemon Wheel', NULL, NULL, NULL),
('Licor Amaretto', NULL, NULL, NULL),
('Licor Frangelico', NULL, NULL, NULL),
('Lillet Blanc', NULL, NULL, NULL),
('Lime Cut Into Small Wedges', NULL, NULL, NULL),
('Lime Juice', NULL, NULL, NULL),
('London Dry Gin', NULL, NULL, NULL),
('Maraschino Luxardo', NULL, NULL, NULL),
('Maraschinoluxardo', NULL, NULL, NULL),
('Martinique Molasses Rhum*', NULL, NULL, NULL),
('Mezcal', NULL, NULL, NULL),
('Mint Leaves', NULL, NULL, NULL),
('Mint Sprigs', NULL, NULL, NULL),
('Monin Honey Syrup', NULL, NULL, NULL),
('Of Absinthe', NULL, NULL, NULL),
('Old Tom Gin', NULL, NULL, NULL),
('Orange Bitters', NULL, NULL, NULL),
('Orange Curacao', NULL, NULL, NULL),
('Orange Flower Water', NULL, NULL, NULL),
('Orange Wheel', NULL, NULL, NULL),
('Orgeat Syrup', NULL, NULL, NULL),
('Palo Cortado', NULL, NULL, NULL),
('Passion Fruit Liqueur', NULL, NULL, NULL),
('Passion Fruit Puree', NULL, NULL, NULL),
('Passion Fruit Syrup', NULL, NULL, NULL),
('Pcs Mint Leaves', NULL, NULL, NULL),
('Peach Brandy', NULL, NULL, NULL),
('Peach Schnapps', NULL, NULL, NULL),
('Pernod', NULL, NULL, NULL),
('Peychaud’s Bitters', NULL, NULL, NULL),
('Pineapple Juice', NULL, NULL, NULL),
('Pink Grapefruit Soda', NULL, NULL, NULL),
('Pisco', NULL, NULL, NULL),
('Plain Water', NULL, NULL, NULL),
('Powdered Sugar', NULL, NULL, NULL),
('Prosecco', NULL, NULL, NULL),
('Raspberry Liqueur', NULL, NULL, NULL),
('Raspberry Syrup', NULL, NULL, NULL),
('Raw Honey', NULL, NULL, NULL),
('Raw Whole Egg White', NULL, NULL, NULL),
('Red Tawny Port Wine', NULL, NULL, NULL),
('Red Wine', NULL, NULL, NULL),
('Rhum Martinique Agricole', NULL, NULL, NULL),
('Ron Profundo Havana Club', NULL, NULL, NULL),
('Ron Smoky Havana Club', NULL, NULL, NULL),
('Rum', NULL, NULL, NULL),
('Rye Whiskey', NULL, NULL, NULL),
('Rye Whiskey or Bourbon', NULL, NULL, NULL),
('Salt', NULL, NULL, NULL),
('Scotch Whisky', NULL, NULL, NULL),
('Simple Syrup', NULL, NULL, NULL),
('Smirnoff Vodka', NULL, NULL, NULL),
('Soda Water', NULL, NULL, NULL),
('Sparkling Wine', NULL, NULL, NULL),
('Strong Espresso', NULL, NULL, NULL),
('Sugar', NULL, NULL, NULL),
('Sugar Cane Juice', NULL, NULL, NULL),
('Sugar Cube', NULL, NULL, NULL),
('Sugar Syrup', NULL, NULL, NULL),
('Superfine Sugar', NULL, NULL, NULL),
('Sweet Red Vermouth', NULL, NULL, NULL),
('Sweet Vermouth', NULL, NULL, NULL),
('Sweet Vermouth Cinzano Rosso', NULL, NULL, NULL),
('Tabasco', NULL, NULL, NULL),
('Tequila', NULL, NULL, NULL),
('Tequila 100% Agave', NULL, NULL, NULL),
('Thin Slices Red Chili Pepper', NULL, NULL, NULL),
('To 4 Pcs Pineapple Chunks', NULL, NULL, NULL),
('Tomato Juice', NULL, NULL, NULL),
('Top With Cola', NULL, NULL, NULL),
('Triple Sec', NULL, NULL, NULL),
('Vanilla Extract', NULL, NULL, NULL),
('Vanilla Sugar', NULL, NULL, NULL),
('Vanilla Vodka', NULL, NULL, NULL),
('Vodka', NULL, NULL, NULL),
('Vodka Citron', NULL, NULL, NULL),
('Vodka Vanilla', NULL, NULL, NULL),
('Water', NULL, NULL, NULL),
('White Cane Sugar', NULL, NULL, NULL),
('White Crème de Menthe', NULL, NULL, NULL),
('White Cuban Ron', NULL, NULL, NULL),
('White Peach Puree', NULL, NULL, NULL),
('White Rum', NULL, NULL, NULL),
('White Smooth Grappa', NULL, NULL, NULL),
('Worcestershire Sauce', NULL, NULL, NULL),
('Yellow Chartreuse', NULL, NULL, NULL);

-- Insert drinks
INSERT INTO drinks (name, description, glass_type, build_method, garnish) VALUES
('Between the Sheets', 'Add all ingredients into a cocktail shaker.
Shake with ice and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Tequila Sunrise', 'Pour tequila and orange juice directly into highball glass filled with ice cubes.
Add the grenadine syrup to create chromatic effect (sunrise), do not stir.', 'Highball', 'Stirred', NULL),
('Paper Plane', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Corpse Reviver #2', 'Pour all ingredients into shaker with ice.
Shake well and strain in chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Mimosa', 'Pour orange juice into flute glass and gently pour the sparkling wine.
Stir gently.
NOTE:Also known as Buck’s Fizz.', 'Flute', 'Stirred', NULL),
('Old Cuban', 'Pour all ingredients into cocktail shaker except the wine, shake well with ice, strain into chilled elegant cocktail glass.
Top up with the sparkling wine.', 'Martini', 'Shaken', NULL),
('Sea Breeze', 'Build all ingredients in a highball glass filled with ice.', 'Highball', 'In Glass', NULL),
('Margarita', 'Add all ingredients into a shaker with ice.
Shake and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('New York Sour', 'Pour all ingredients into the shaker. Shake vigorously with ice.
Strain into a chilled rocks glass filled with ice. Float the wine on top.', 'Rocks', 'Shaken', NULL),
('Lemon Drop Martini', 'Pour all ingredients into a shaker with ice.
Shake well and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Dark ‘N’ Stormy', 'In a highball glass filled with ice pour the ginger beer and top floating with the Rum.', 'Highball', 'In Glass', NULL),
('Naked and Famous', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Moscow Mule', 'In an Mule Cup or rocks glass, combine the vodka and ginger beer.
Add lime juice and gently stir to involve all ingredients.', 'Rocks', 'Stirred', NULL),
('Fernandito', 'Pour the Fernet Branca into a double old fashioned glass with ice, fill the glass up with Cola. Gently stir.', 'Rocks', 'Stirred', NULL),
('French Connection', 'Pour all ingredients directly into old fashioned glass filled with ice cubes.
Stir gently.', 'Rocks', 'Stirred', NULL),
('Kir', 'Pour Crème de Cassis into glass, top up with white wine.
NOTE:Kir Royal – Use Champagne instead of white wine', 'Flute', NULL, NULL),
('Pisco Sour', 'Add all ingredients into a shaker with ice.
Shake and strain into a chilled goblet glass.', 'Coupe', 'Shaken', NULL),
('Russian Spring Punch', 'Pour all ingredients into cocktail shaker except the sparkling wine, shake well with ice, strain into chilled tall tumbler glass filled with ice
and top up with sparkling wine.', 'Highball', 'Shaken', NULL),
('Caipirinha', 'Place lime and sugar into a double old fashioned glass and muddle gently.
Fill the glass with cracked ice and add Cachaça. Stir gently to involve ingredients.
Note:Caipiroska – Instead of Cachaça use ', 'Rocks', 'Stirred', NULL),
('Gin Fizz', 'Shake all ingredients with ice except soda water.
Pour into thin tall Tumbler glass , top with a splash soda water.
NOTE:Serve without ice.', 'Highball', 'Shaken', NULL),
('Clover Club', 'Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Old Fashioned', 'Place sugar cube in old fashioned glass and saturate with bitter, add few dashes of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey.
Stir gently.', 'Rocks', 'Stirred', NULL),
('Brandy Crusta', 'Mix together all ingredients with ice cubes in a mixing
glass and strain into a prepared slim cocktail glass.', 'Martini', NULL, NULL),
('Long Island Iced Tea', 'Add all ingredients into highball glass filled with ice.
Stir gently.', 'Highball', 'Stirred', NULL),
('Espresso Martini', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Bloody Mary', 'Stir gently all the ingredients in a mixing glass with ice, pour into rocks glass.
NOTE:If requested served with ice, pour into highball glass.', 'Rocks', 'Stirred', NULL),
('Sex on the Beach', 'Build all ingredients in a highball glass filled with ice.', 'Highball', 'In Glass', NULL),
('Irish Coffee', 'Warm black coffee is poured into a preheated Irish coffee glass.
Whiskey and at least one teaspoon of sugar is added and stirred until dissolved.
Fresh thick chilled cream is carefully poured over the', NULL, 'Stirred', NULL),
('Manhattan', 'Pour all ingredients into mixing glass with ice cubes.
Stir well. Strain into chilled cocktail glass.', 'Martini', 'Stirred', NULL),
('Grasshopper', 'Pour all ingredients into shaker filled with ice.
Shake briskly for few seconds. Strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Tuxedo', 'Pour all ingredients into mixing glass with ice cubes. Stir well.
Strain into chilled martini cocktail glass.', 'Martini', 'Stirred', NULL),
('Stinger', 'Pour all ingredients into mixing glass with ice cubes. Stir well.
Strain into chilled martini cocktail glass.', 'Martini', 'Stirred', NULL),
('Garibaldi', 'Build all ingredients in a highball glass filled with ice.', 'Highball', 'In Glass', NULL),
('Jungle Bird', 'Pour all ingredients into a shaker with ice and shake.
Strain into a rocks glass filled with ice.', 'Rocks', 'Shaken', NULL),
('Martinez', 'Pour all ingredients into mixing glass with ice cubes.
Stir well. Strain into chilled cocktail glass.', 'Martini', 'Stirred', NULL),
('Paradise', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Bramble', 'Pour all ingredients into cocktail shaker except the Crème de Mûre, shake well with ice, strain into chilled old fashioned glass filled with crushed ice, then pour the blackberry liqueur (Crème de Mûr', 'Rocks', 'Shaken', NULL),
('Singapore Sling', 'Pour all ingredients into cocktail shaker filled with ice cubes.
Shake well.
Strain into Hurricane glass.', 'Hurricane', 'Shaken', NULL),
('Hemingway Special', 'Pour all ingredients into a shaker with ice.
Shake well and strain into a large cocktail glass.', 'Martini', 'Shaken', NULL),
('Boulevardier', 'Pour all ingredients into mixing glass with ice cubes.
Stir well. Strain into chilled cocktail glass.', 'Martini', 'Stirred', NULL),
('Don’s Special Daiquiri', 'Blend for a few seconds in a milkshake mixer with  crushed ice and pour into a footed copo glass.
Fill the glass with more crushed ice.', 'Copo', 'Shaken', NULL),
('Mary Pickford', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Last Word', 'Add all ingredients into a cocktail shaker.
Shake with ice and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Pina Colada', 'Blend all the ingredients with ice in a electric blender,
pour into a large glass and serve with straws.
Note:Historically a few drops of fresh lime juice was added to taste. 4 slices of fresh pineapp', NULL, 'Blended', 'Pineapple'),
('Rusty Nail', 'Pour all ingredients directly into an old fashioned glass filled with ice.
Stir gently.', 'Rocks', 'Stirred', NULL),
('John Collins', 'Pour all ingredients directly into highball filled with ice. Stir gently.
NOTE:Use ‘Old Tom’ Gin for Tom Collins.', 'Highball', 'Stirred', NULL),
('Paloma', 'Poor the tequila into a highball glass, squeeze the lime juice.
Add ice and salt, fill up pink grapefruit soda.
Stir gently.', 'Highball', 'Stirred', NULL),
('Ve.N.To', 'Pour all ingredients into the shaker. Shake vigorously with ice.
Strain into a chilled small tumbler glass filled with ice.
NOTE:*If desired water can be replaced by chamomile infusion in the honey mi', 'Highball', 'Shaken', NULL),
('Sazerac', 'Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice in a mixing glass.
Discard the ice and any excess absinthe from the pre', 'Rocks', 'Stirred', NULL),
('Negroni', 'Pour all ingredients directly into chilled old fashioned glass filled with ice.
Stir gently.', 'Rocks', 'Stirred', NULL),
('Porn Star Martini', 'Pour all ingredients into cocktail shaker, shake well with ice, double strain into a large chilled cocktail glass.
Accompany with a shot of champagne.', 'Martini', 'Shaken', NULL),
('Tommy’s Margarita', 'Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled rocks glass filled with ice.', 'Rocks', 'Shaken', NULL),
('Remember the Maine', 'Pour the absinthe into a coupe glass and swirl to completely coat the inside.
Discard the absinthe and set the glass aside. Add the other ingredients to a mixing glass and fill it 3/4 full with ice. S', 'Coupe', 'Stirred', NULL),
('Rabo de Galo', 'Combine all the ingredients into a rocks glass, add ice and stir briefly.', 'Rocks', 'Stirred', NULL),
('Gin Basil Smash', 'Add all ingredients into shaker with ice.
Shake vigorously and pour into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Mojito', 'Mix mint springs with sugar and lime juice.
Add splash of soda water and fill the glass with ice.
Pour the rum and top with soda water. Light stir to involve all ingredients.', NULL, 'Stirred', 'Mint'),
('Grand Margarita', 'Rim the rock glass with good quality sea salt. Pour the ingredients into the  shaker.
Add ice to both glass and shaker.
Shake hard for 10 seconds. Strain the drink into the glass.', NULL, 'Shaken', NULL),
('Illegal', 'Pour all ingredients into the shaker. Shake vigorously with ice.
Strain into a chilled cocktail glass, or “on the rocks” in a traditional clay or terracotta mug.', 'Martini', 'Shaken', NULL),
('Pisco Punch', 'Gentle mash the simple syrup with the cloves, add the remaining ingredients except the wine.
Shake vigorously and double strain into a large goblet.
Add the wine on top and gently stir.', 'Coupe', 'Shaken', NULL),
('Mint Julep', 'In Julep Stainless Steel Cup gently muddle the mint with sugar and water.
Fill the glass with cracked ice, add the Bourbon and stir well until the cup frosts.', 'Julep', 'Stirred', 'Mint'),
('Horse’s Neck', 'Pour Cognac and ginger ale directly into highball glass with ice cubes.
Stir gently.
If preferred, add dashes of Angostura Bitter.', 'Highball', 'Stirred', NULL),
('Mai-Tai', 'Add all ingredients into a shaker with ice.
Shake and pour into a double rocks glass or an highball glass.
* The Martinique molasses rum used by Trader Vic was not an Agricole Rhum but a type of “rumm', 'Martini', 'Shaken', NULL),
('Porto Flip', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Planters Punch', 'Pour all ingredients directly in a small tumbler or a typical terracotta glass.
NOTE:Add dilution up to taste, it can be given by water, ice or fresh juices.', 'Highball', NULL, NULL),
('Canchanchara', 'Mix honey with water and lime juice and spread the mixture on the bottom and sides of the glass.
Add cracked ice, and then the rum.
End by energetically stirring from bottom to top.', NULL, 'Stirred', NULL),
('Ramos Fizz', 'Pour all ingredients except soda water in a cocktail shaker with ice.
Shake for two minutes, double strain in a glass, pour the drink back in the shaker and hard shake without ice for one minute.
Stra', 'Highball', 'Shaken', NULL),
('Bellini', 'Pour peach puree into the mixing glass with ice, add the Prosecco wine.
Stir gently and pour in a chilled flute glass.
NOTE:Puccini – Fresh Mandarin Orange Juice;Rossini – Fresh Strawberry Puree;Tinto', 'Flute', 'Stirred', NULL),
('Cosmopolitan', 'Add all ingredients into cocktail shaker filled with ice.
Shake well and strain into large cocktail glass.', 'Martini', 'Shaken', NULL),
('Whiskey Sour', 'Pour all ingredients into cocktail shaker filled with ice. Shake well.
Strain into cobbler glass. If served “On the rocks”, strain ingredients
into old fashioned glass filled with ice.
NOTE:If egg whi', 'Rocks', 'Shaken', NULL),
('Cardinale', 'Pour all ingredients into mixing glass with ice cubes. Stir well.
Strain into chilled cocktail glass.', 'Martini', 'Stirred', NULL),
('Aviation', 'Add all ingredients into a cocktail shaker.
Shake with cracked ice and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Trinidad Sour', 'Pour all ingredients into a cocktail shaker, shake well with ice.
Strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Black Russian', 'Pour the ingredients into the old fashioned glass filled with ice cubes.
Stir gently. strain ingredients into old fashioned glass filled with ice.
NOTE:WHITE RUSSIAN – Float fresh cream on the top and', 'Rocks', 'Stirred', NULL),
('Champagne Cocktail', 'Place the sugar cube with 2 dashes of bitters in a large Champagne glass, add the cognac.
Pour gently chilled Champagne.', 'Flute', NULL, NULL),
('Suffering Bastard', 'Pour all ingredients into cocktail shaker except the ginger beer, shake well with ice.
Pour unstrained into a Collins glass or in the original.
S. Bastard mug and top up with ginger beer.', 'Highball', 'Shaken', NULL),
('French Martini', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Casino', 'Pour all ingredients into cocktails shaker, shake well with ice, strain
into chilled rocks glass with ice.', 'Rocks', 'Shaken', NULL),
('Sidecar', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('White Lady', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Bee’s Knees', 'Stir honey with lemon and orange juices until it dissolves, add gin and shake with ice. Strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Cuba Libre', 'Build all ingredients in a highball glass filled with ice.', 'Highball', 'In Glass', NULL),
('Tipperary', 'Pour all ingredients into mixing glass with ice cubes.
Stir well. Strain into chilled martini cocktail glass.', 'Martini', 'Stirred', NULL),
('IBA Tiki', 'In a cocktail shaker muddle a thin slice of Gengibre, Pour all other ingredients.
Shake vigorously with ice.
Strain into a chilled Tiki glass filled with pebbled ice.', NULL, 'Shaken', NULL),
('Chartreuse Swizzle', 'Pour all ingredients into a tall glass, add pebble ice.
With the help of a swizzle stick (or cocktail spoon) mix vigorously, complete by filling the glass with more pebble ice.', NULL, 'In Glass', NULL),
('Zombie', 'Add all ingredients into an electric blender with 170 grams of cracked ice.
With pulse bottom blend for a few seconds. Serve in a tall tumbler glass.
Note:*Donn’s Mix: 2 parts of fresh yellow grapefru', 'Highball', 'Blended', NULL),
('Angel Face', 'Pour all ingredients into cocktail shaker filled with ice cubes.
Shake and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('French 75', 'Pour all the ingredients, except Champagne, into a shaker.
Shake well and strain into a Champagne flute.
Top up with Champagne.
Stir gently.', 'Flute', 'Shaken', NULL),
('Vesper', 'Pour all ingredients into cocktail shaker filled with ice cubes.
Shake and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Sherry Cobbler', 'Combine sherry, sugar and 2 quarter wheels each of orange and lemon in a shaker with ice, shake briskly, strain into a Julep cocktail cup filled with crushed ice.', 'Julep', 'Shaken', NULL),
('South Side', 'Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.
Note:If egg white is used shake vigorously.', 'Martini', 'Shaken', NULL),
('Spritz', 'Build all ingredients into a wine glass filled with ice.
Stir gently.
NOTE:There are other versions of the Spritz that use Campari, Cynar or Select instead of Aperol.', NULL, 'Stirred', NULL),
('Penicillin', 'Muddle fresh ginger in a shaker and add the remaining ingredients except for the Islay single malt whisky.
Fill the shaker with ice and shake.
Fine train into a chilled Old Fashioned glass with ice.
F', 'Rocks', 'Shaken', NULL),
('Monkey Gland', 'Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Missionary’s Downfall', 'Blend all the ingredients with half cup of crushed ice.
Serve it in a Coppa grande.', NULL, 'Blended', NULL),
('Dry Martini', 'Pour all ingredients into mixing glass with ice cubes. Stir well.
Strain into chilled martini cocktail glass.', 'Martini', 'Stirred', NULL),
('Three Dots and a Dash', 'Pour all ingredients in a Blender with 12 ounces of crushed ice, flash blend, pour the drink into a footed copo glass.
Fill the glass with more crushed ice.', 'Copo', 'In Glass', NULL),
('Hanky Panky', 'Pour all ingredients into mixing glass with ice cubes. Stir well.
Strain into chilled cocktail glass.', 'Martini', 'Stirred', NULL),
('Americano', 'Mix the ingredients directly in an old fashioned glass filled with ice cubes.
Add a splash of Soda Water. Stir gently.', 'Rocks', 'Stirred', NULL),
('Vieux Carré', 'Pour all ingredients into mixing glass with ice cubes.
Stir well. Strain into chilled cocktail glass.', 'Martini', 'Stirred', NULL),
('Spicy Fifty', 'Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Daiquiri', 'In a cocktail shaker add all ingredients. Stir well to dissolve the sugar.
Add ice and shake. Strain into chilled cocktail glass.', 'Martini', 'Shaken', NULL),
('Alexander', 'Pour all ingredients into cocktail shaker filled with ice cubes.
Shake and strain into a chilled cocktail glass.', 'Martini', 'Shaken', NULL);

-- Insert drink_ingredients relationships
INSERT INTO drink_ingredients (drink_id, ingredient_id, amount, unit) VALUES
((SELECT drink_id FROM drinks WHERE name = 'Between the Sheets'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Rum'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Between the Sheets'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Between the Sheets'), (SELECT ingredient_id FROM ingredients WHERE name = 'Triple Sec'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Between the Sheets'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tequila Sunrise'), (SELECT ingredient_id FROM ingredients WHERE name = 'Tequila'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tequila Sunrise'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Orange Juice'), '3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tequila Sunrise'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grenadine Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paper Plane'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bourbon Whiskey'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paper Plane'), (SELECT ingredient_id FROM ingredients WHERE name = 'Amaro Nonino'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paper Plane'), (SELECT ingredient_id FROM ingredients WHERE name = 'Aperol'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paper Plane'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Corpse Reviver #2'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Corpse Reviver #2'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cointreau'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Corpse Reviver #2'), (SELECT ingredient_id FROM ingredients WHERE name = 'Lillet Blanc'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Corpse Reviver #2'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Corpse Reviver #2'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dash Absinthe'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Mimosa'), (SELECT ingredient_id FROM ingredients WHERE name = 'Freshly Squeezed Orange Juice'), '2.50', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mimosa'), (SELECT ingredient_id FROM ingredients WHERE name = 'Prosecco'), '2.50', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Old Cuban'), (SELECT ingredient_id FROM ingredients WHERE name = 'Pcs Mint Leaves'), '6/8', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Old Cuban'), (SELECT ingredient_id FROM ingredients WHERE name = 'Aged Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Old Cuban'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Old Cuban'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Old Cuban'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Old Cuban'), (SELECT ingredient_id FROM ingredients WHERE name = 'Brut Champagne or Prosecco'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sea Breeze'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sea Breeze'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cranberry Juice'), '4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sea Breeze'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grapefruit Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Tequila 100% Agave'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Triple Sec'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Freshly Squeezed Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'New York Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Rye Whiskey or Bourbon'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'New York Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'New York Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'New York Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg White'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'New York Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Red Wine'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Lemon Drop Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Lemon Drop Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Triple Sec'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Lemon Drop Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Squeezed Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Dark ‘N’ Stormy'), (SELECT ingredient_id FROM ingredients WHERE name = 'Goslings Rum'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Dark ‘N’ Stormy'), (SELECT ingredient_id FROM ingredients WHERE name = 'Ginger Beer'), '3.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Naked and Famous'), (SELECT ingredient_id FROM ingredients WHERE name = 'Mezcal'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Naked and Famous'), (SELECT ingredient_id FROM ingredients WHERE name = 'Yellow Chartreuse'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Naked and Famous'), (SELECT ingredient_id FROM ingredients WHERE name = 'Aperol'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Naked and Famous'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Moscow Mule'), (SELECT ingredient_id FROM ingredients WHERE name = 'Smirnoff Vodka'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Moscow Mule'), (SELECT ingredient_id FROM ingredients WHERE name = 'Ginger Beer'), '4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Moscow Mule'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Fernandito'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fernet Branca'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Fernandito'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cola'), 'top', 'up'),
((SELECT drink_id FROM drinks WHERE name = 'French Connection'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1.17', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'French Connection'), (SELECT ingredient_id FROM ingredients WHERE name = 'Amaretto'), '1.17', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Kir'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dry White Wine'), '3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Kir'), (SELECT ingredient_id FROM ingredients WHERE name = 'Crème de Cassis'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Pisco'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Raw Whole Egg White'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Russian Spring Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '0.83', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Russian Spring Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '0.83', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Russian Spring Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Creme de Cassis'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Russian Spring Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Syrup'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Russian Spring Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sparkling Wine'), 'top', 'up'),
((SELECT drink_id FROM drinks WHERE name = 'Caipirinha'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cachaça'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Caipirinha'), (SELECT ingredient_id FROM ingredients WHERE name = 'Lime Cut Into Small Wedges'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Caipirinha'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Cane Sugar'), '4', 'teaspoons'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Soda Water'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Clover Club'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Clover Club'), (SELECT ingredient_id FROM ingredients WHERE name = 'Raspberry Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Clover Club'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Clover Club'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg White'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Old Fashioned'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bourbon or Rye Whiskey'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Old Fashioned'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Cube'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Old Fashioned'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '1', 'dash'),
((SELECT drink_id FROM drinks WHERE name = 'Old Fashioned'), (SELECT ingredient_id FROM ingredients WHERE name = 'Plain Water'), '1', 'dash'),
((SELECT drink_id FROM drinks WHERE name = 'Brandy Crusta'), (SELECT ingredient_id FROM ingredients WHERE name = 'Brandy'), '1.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Brandy Crusta'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschinoluxardo'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Brandy Crusta'), (SELECT ingredient_id FROM ingredients WHERE name = 'Curacao'), '1', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Brandy Crusta'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Brandy Crusta'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Brandy Crusta'), (SELECT ingredient_id FROM ingredients WHERE name = 'Aromatic Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'Tequila'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Rum'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cointreau'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'Lemon Juice'), '0.83', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Long Island Iced Tea'), (SELECT ingredient_id FROM ingredients WHERE name = 'Top With Cola'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Espresso Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Espresso Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Kahlúa'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Espresso Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Syrup'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Espresso Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Strong Espresso'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Bloody Mary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bloody Mary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Tomato Juice'), '3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bloody Mary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bloody Mary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Worcestershire Sauce'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Bloody Mary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Tabasco'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Sex on the Beach'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sex on the Beach'), (SELECT ingredient_id FROM ingredients WHERE name = 'Peach Schnapps'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sex on the Beach'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Orange Juice'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sex on the Beach'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cranberry Juice'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Irish Coffee'), (SELECT ingredient_id FROM ingredients WHERE name = 'Irish Whiskey'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Irish Coffee'), (SELECT ingredient_id FROM ingredients WHERE name = 'Hot Coffee'), '4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Irish Coffee'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Cream'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Irish Coffee'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar'), '1', 'teaspoon'),
((SELECT drink_id FROM drinks WHERE name = 'Manhattan'), (SELECT ingredient_id FROM ingredients WHERE name = 'Rye Whiskey'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Manhattan'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Red Vermouth'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Manhattan'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dash Angostura Bitters'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Grasshopper'), (SELECT ingredient_id FROM ingredients WHERE name = 'Crème de Cacao'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Grasshopper'), (SELECT ingredient_id FROM ingredients WHERE name = 'Crème de Menthe'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Grasshopper'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Cream'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tuxedo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Old Tom Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tuxedo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dry Vermouth'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tuxedo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschino Luxardo'), '1/2', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Tuxedo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Of Absinthe'), '1/4', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Tuxedo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orange Bitters'), '3', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Stinger'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Stinger'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Crème de Menthe'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Garibaldi'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bitter Campari'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Garibaldi'), (SELECT ingredient_id FROM ingredients WHERE name = 'Freshly Squeezed Orange Juice'), '4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Jungle Bird'), (SELECT ingredient_id FROM ingredients WHERE name = 'Blackstrap Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Jungle Bird'), (SELECT ingredient_id FROM ingredients WHERE name = 'Campari'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Jungle Bird'), (SELECT ingredient_id FROM ingredients WHERE name = 'Pineapple Juice'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Jungle Bird'), (SELECT ingredient_id FROM ingredients WHERE name = 'Freshly Squeezed Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Jungle Bird'), (SELECT ingredient_id FROM ingredients WHERE name = 'Demerara Sugar Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Martinez'), (SELECT ingredient_id FROM ingredients WHERE name = 'London Dry Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Martinez'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Red Vermouth'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Martinez'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschinoluxardo'), '1', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Martinez'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orange Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Paradise'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paradise'), (SELECT ingredient_id FROM ingredients WHERE name = 'Apricot Brandy'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paradise'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Orange Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bramble'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bramble'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '0.83', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bramble'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Syrup'), '0.42', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bramble'), (SELECT ingredient_id FROM ingredients WHERE name = 'Crème de Mûre'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cherry Sangue Morlacco'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cointreau'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'DOM Bénédictine'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Pineapple Juice'), '4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grenadine Syrup'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Singapore Sling'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '1', 'dash'),
((SELECT drink_id FROM drinks WHERE name = 'Hemingway Special'), (SELECT ingredient_id FROM ingredients WHERE name = 'Rum'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Hemingway Special'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grapefruit Juice'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Hemingway Special'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschino Luxardo'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Hemingway Special'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Boulevardier'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bourbon or Rye Whiskey'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Boulevardier'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bitter Campari'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Boulevardier'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Red Vermouth'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Don’s Special Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gold Jamaican Rum'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Don’s Special Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cuban Rum'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Don’s Special Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'Passion Fruit Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Don’s Special Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Don’s Special Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'Honey Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mary Pickford'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mary Pickford'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Pineapple Juice'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mary Pickford'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschino Luxardo'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mary Pickford'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grenadine Syrup'), '1', 'barspoon'),
((SELECT drink_id FROM drinks WHERE name = 'Last Word'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Last Word'), (SELECT ingredient_id FROM ingredients WHERE name = 'Green Chartreuse'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Last Word'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschinoluxardo'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Last Word'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pina Colada'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pina Colada'), (SELECT ingredient_id FROM ingredients WHERE name = 'Coconut Cream'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pina Colada'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Pineapple Juice'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Rusty Nail'), (SELECT ingredient_id FROM ingredients WHERE name = 'Scotch Whisky'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Rusty Nail'), (SELECT ingredient_id FROM ingredients WHERE name = 'Drambuie'), '0.83', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'John Collins'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'John Collins'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'John Collins'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'John Collins'), (SELECT ingredient_id FROM ingredients WHERE name = 'Soda Water'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paloma'), (SELECT ingredient_id FROM ingredients WHERE name = '100% Agave Tequila'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Paloma'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime'), '1', 'barspoon'),
((SELECT drink_id FROM drinks WHERE name = 'Paloma'), (SELECT ingredient_id FROM ingredients WHERE name = 'Salt'), '1', 'pinch'),
((SELECT drink_id FROM drinks WHERE name = 'Paloma'), (SELECT ingredient_id FROM ingredients WHERE name = 'Pink Grapefruit Soda'), '3.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ve.N.To'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Smooth Grappa'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ve.N.To'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ve.N.To'), (SELECT ingredient_id FROM ingredients WHERE name = 'Honey Mix (replace Water With Chamomile)*'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ve.N.To'), (SELECT ingredient_id FROM ingredients WHERE name = 'Chamomile Cordial'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ve.N.To'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg White'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Sazerac'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sazerac'), (SELECT ingredient_id FROM ingredients WHERE name = 'Absinthe'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sazerac'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Cube'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Sazerac'), (SELECT ingredient_id FROM ingredients WHERE name = 'Peychaud’s Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Negroni'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Negroni'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bitter Campari'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Negroni'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Red Vermouth'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Porn Star Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vanilla Vodka'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Porn Star Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Passion Fruit Liqueur'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Porn Star Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Passion Fruit Puree'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Porn Star Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vanilla Sugar'), '2', 'bar spoons'),
((SELECT drink_id FROM drinks WHERE name = 'Porn Star Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Champagne'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tommy’s Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Tequila 100% Agave'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tommy’s Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tommy’s Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Agave Nectar'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Remember the Maine'), (SELECT ingredient_id FROM ingredients WHERE name = 'Rye Whiskey'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Remember the Maine'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Vermouth'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Remember the Maine'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cherry Brandy Luxardo'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Remember the Maine'), (SELECT ingredient_id FROM ingredients WHERE name = 'Absinthe'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Rabo de Galo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cachaca'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Rabo de Galo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Vermouth Cinzano Rosso'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Rabo de Galo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cynar'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Rabo de Galo'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura'), '2', 'drops'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Basil Smash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Basil Smash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Freshly Squeezed Lemon Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Basil Smash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Syrup'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Gin Basil Smash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Italian Basil Leaves'), '10', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Mojito'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Cuban Ron'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mojito'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mojito'), (SELECT ingredient_id FROM ingredients WHERE name = 'Mint Sprigs'), '6', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Mojito'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Cane Sugar'), '2', 'tsp'),
((SELECT drink_id FROM drinks WHERE name = 'Mojito'), (SELECT ingredient_id FROM ingredients WHERE name = 'Soda Water'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Grand Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Tequila 100% Agave'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Grand Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grand Marnier'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Grand Margarita'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Illegal'), (SELECT ingredient_id FROM ingredients WHERE name = 'Espadin Mezcal'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Illegal'), (SELECT ingredient_id FROM ingredients WHERE name = 'Jamaica Overproof White Rum'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Illegal'), (SELECT ingredient_id FROM ingredients WHERE name = 'Falernum'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Illegal'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschino Luxardo'), '1', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Illegal'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Illegal'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Illegal'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg White'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Pisco'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Pineapple Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dry White Wine'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Pisco Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cloves'), '3', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Mint Julep'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bourbon Whiskey'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mint Julep'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Mint Sprigs'), '4', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Mint Julep'), (SELECT ingredient_id FROM ingredients WHERE name = 'Powdered Sugar'), '1', 'tsp'),
((SELECT drink_id FROM drinks WHERE name = 'Mint Julep'), (SELECT ingredient_id FROM ingredients WHERE name = 'Water'), '2', 'tsp'),
((SELECT drink_id FROM drinks WHERE name = 'Horse’s Neck'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Horse’s Neck'), (SELECT ingredient_id FROM ingredients WHERE name = 'Ginger Ale'), '4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Horse’s Neck'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dash of Angostura Bitters'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Mai-Tai'), (SELECT ingredient_id FROM ingredients WHERE name = 'Amber Jamaican Rum'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mai-Tai'), (SELECT ingredient_id FROM ingredients WHERE name = 'Martinique Molasses Rhum*'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mai-Tai'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orange Curacao'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mai-Tai'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orgeat Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mai-Tai'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Squeezed Lime Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Mai-Tai'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Porto Flip'), (SELECT ingredient_id FROM ingredients WHERE name = 'Brandy'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Porto Flip'), (SELECT ingredient_id FROM ingredients WHERE name = 'Red Tawny Port Wine'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Porto Flip'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg Yolk'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Planters Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Jamaican Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Planters Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Planters Punch'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Cane Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Canchanchara'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cuban Aguardiente'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Canchanchara'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Canchanchara'), (SELECT ingredient_id FROM ingredients WHERE name = 'Raw Honey'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Canchanchara'), (SELECT ingredient_id FROM ingredients WHERE name = 'Water'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Syrup'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cream'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg White'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orange Flower Water'), '3', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vanilla Extract'), '2', 'drops'),
((SELECT drink_id FROM drinks WHERE name = 'Ramos Fizz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Soda Water'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Bellini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Prosecco'), '3.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bellini'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Peach Puree'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cosmopolitan'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka Citron'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cosmopolitan'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cointreau'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cosmopolitan'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cosmopolitan'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cranberry Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Whiskey Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bourbon Whiskey'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Whiskey Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '0.83', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Whiskey Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Syrup'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Whiskey Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg White'), '1', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Cardinale'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cardinale'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dry Vermouth'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cardinale'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bitter Campari'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Aviation'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Aviation'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschinoluxardo'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Aviation'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Aviation'), (SELECT ingredient_id FROM ingredients WHERE name = 'Crème de Violette'), '1', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Trinidad Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Trinidad Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orgeat Syrup'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Trinidad Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Trinidad Sour'), (SELECT ingredient_id FROM ingredients WHERE name = 'Rye Whiskey'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Black Russian'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Black Russian'), (SELECT ingredient_id FROM ingredients WHERE name = 'Coffee Liqueur'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Champagne Cocktail'), (SELECT ingredient_id FROM ingredients WHERE name = 'Chilled Champagne'), '3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Champagne Cocktail'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Champagne Cocktail'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Champagne Cocktail'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grand Marnier'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Champagne Cocktail'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Cube'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Suffering Bastard'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac or Brandy'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Suffering Bastard'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Suffering Bastard'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Suffering Bastard'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Suffering Bastard'), (SELECT ingredient_id FROM ingredients WHERE name = 'Ginger Beer'), 'top', 'up'),
((SELECT drink_id FROM drinks WHERE name = 'French Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'French Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Raspberry Liqueur'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'French Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Pineapple Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Casino'), (SELECT ingredient_id FROM ingredients WHERE name = 'Old Tom Gin'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Casino'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschinoluxardo'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Casino'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Casino'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orange Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Sidecar'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sidecar'), (SELECT ingredient_id FROM ingredients WHERE name = 'Triple Sec'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sidecar'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'White Lady'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1.33', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'White Lady'), (SELECT ingredient_id FROM ingredients WHERE name = 'Triple Sec'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'White Lady'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bee’s Knees'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dry Gin'), '1.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bee’s Knees'), (SELECT ingredient_id FROM ingredients WHERE name = 'Honey Syrup'), '2', 'teaspoons'),
((SELECT drink_id FROM drinks WHERE name = 'Bee’s Knees'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Bee’s Knees'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Orange Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cuba Libre'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cuba Libre'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cola'), '4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Cuba Libre'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tipperary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Irish Whiskey'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tipperary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Red Vermouth'), '0.83', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tipperary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Green Chartreuse'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Tipperary'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Ron Profundo Havana Club'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Ron Smoky Havana Club'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Licor Amaretto'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Licor Frangelico'), '1', 'barspoon'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Maraschino Luxardo'), '5', 'drops'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Passion Fruit Puree'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Pineapple Juice'), '90', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '30', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'IBA Tiki'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gengibre Slice'), '1', 'pc'),
((SELECT drink_id FROM drinks WHERE name = 'Chartreuse Swizzle'), (SELECT ingredient_id FROM ingredients WHERE name = 'Green Chartreuse'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Chartreuse Swizzle'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Pineapple Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Chartreuse Swizzle'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Chartreuse Swizzle'), (SELECT ingredient_id FROM ingredients WHERE name = 'Falernum'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Jamaican Dark Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gold Puerto Rican Rum'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Demerara Rum'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Falernum'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Donn’s Mix*'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grenadine Syrup'), '1', 'tsp'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dash Angostura Bitters'), '1', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Zombie'), (SELECT ingredient_id FROM ingredients WHERE name = 'Pernod'), '6', 'drops'),
((SELECT drink_id FROM drinks WHERE name = 'Angel Face'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Angel Face'), (SELECT ingredient_id FROM ingredients WHERE name = 'Apricot Brandy'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Angel Face'), (SELECT ingredient_id FROM ingredients WHERE name = 'Calvados'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'French 75'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'French 75'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'French 75'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sugar Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'French 75'), (SELECT ingredient_id FROM ingredients WHERE name = 'Champagne'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Vesper'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Vesper'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Vesper'), (SELECT ingredient_id FROM ingredients WHERE name = 'Lillet Blanc'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sherry Cobbler'), (SELECT ingredient_id FROM ingredients WHERE name = 'Amontillado Sherry'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sherry Cobbler'), (SELECT ingredient_id FROM ingredients WHERE name = 'Palo Cortado'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Sherry Cobbler'), (SELECT ingredient_id FROM ingredients WHERE name = 'Superfine Sugar'), '1', 'tsp'),
((SELECT drink_id FROM drinks WHERE name = 'Sherry Cobbler'), (SELECT ingredient_id FROM ingredients WHERE name = 'Orange Wheel'), '1/2', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Sherry Cobbler'), (SELECT ingredient_id FROM ingredients WHERE name = 'Lemon Wheel'), '1/2', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'South Side'), (SELECT ingredient_id FROM ingredients WHERE name = 'London Dry Gin'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'South Side'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'South Side'), (SELECT ingredient_id FROM ingredients WHERE name = 'Simple Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'South Side'), (SELECT ingredient_id FROM ingredients WHERE name = 'Mint Leaves'), '5/6', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'South Side'), (SELECT ingredient_id FROM ingredients WHERE name = 'Egg White'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Spritz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Prosecco'), '3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Spritz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Aperol'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Spritz'), (SELECT ingredient_id FROM ingredients WHERE name = 'Soda Water'), 'splash', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Penicillin'), (SELECT ingredient_id FROM ingredients WHERE name = 'Blended Scotch Whisky'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Penicillin'), (SELECT ingredient_id FROM ingredients WHERE name = 'Lagavulin 16y'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Penicillin'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lemon Juice'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Penicillin'), (SELECT ingredient_id FROM ingredients WHERE name = 'Honey Syrup'), '0.75', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Penicillin'), (SELECT ingredient_id FROM ingredients WHERE name = '2-3 Quarter Size Sliced Fresh Ginger'), '1', 'unit'),
((SELECT drink_id FROM drinks WHERE name = 'Monkey Gland'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dry Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Monkey Gland'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Orange Juice'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Monkey Gland'), (SELECT ingredient_id FROM ingredients WHERE name = 'Absinthe'), '1', 'tablespoon'),
((SELECT drink_id FROM drinks WHERE name = 'Monkey Gland'), (SELECT ingredient_id FROM ingredients WHERE name = 'Grenadine Syrup'), '1', 'tablespoon'),
((SELECT drink_id FROM drinks WHERE name = 'Missionary’s Downfall'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Rum'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Missionary’s Downfall'), (SELECT ingredient_id FROM ingredients WHERE name = 'Peach Brandy'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Missionary’s Downfall'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Missionary’s Downfall'), (SELECT ingredient_id FROM ingredients WHERE name = 'Honey Mix'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Missionary’s Downfall'), (SELECT ingredient_id FROM ingredients WHERE name = 'Mint Leaves'), '10', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Missionary’s Downfall'), (SELECT ingredient_id FROM ingredients WHERE name = 'To 4 Pcs Pineapple Chunks'), '3', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Dry Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Gin'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Dry Martini'), (SELECT ingredient_id FROM ingredients WHERE name = 'Dry Vermouth'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Three Dots and a Dash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Rhum Martinique Agricole'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Three Dots and a Dash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Blended Aged Rum'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Three Dots and a Dash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Falernum'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Three Dots and a Dash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Allspice Saint Elizabeth15 Ml Fresh Lime Juice'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Three Dots and a Dash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Orange Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Three Dots and a Dash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Honey Syrup'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Three Dots and a Dash'), (SELECT ingredient_id FROM ingredients WHERE name = 'Angostura Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Hanky Panky'), (SELECT ingredient_id FROM ingredients WHERE name = 'London Dry Gin'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Hanky Panky'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Red Vermouth'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Hanky Panky'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fernet'), '1/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Americano'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bitter Campari'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Americano'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Red Vermouth'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Americano'), (SELECT ingredient_id FROM ingredients WHERE name = 'Soda Water'), '1', 'splash'),
((SELECT drink_id FROM drinks WHERE name = 'Vieux Carré'), (SELECT ingredient_id FROM ingredients WHERE name = 'Rye Whiskey'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Vieux Carré'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Vieux Carré'), (SELECT ingredient_id FROM ingredients WHERE name = 'Sweet Vermouth'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Vieux Carré'), (SELECT ingredient_id FROM ingredients WHERE name = 'Bénédictine'), '1', 'bar spoon'),
((SELECT drink_id FROM drinks WHERE name = 'Vieux Carré'), (SELECT ingredient_id FROM ingredients WHERE name = 'Peychaud’s Bitters'), '2', 'dashes'),
((SELECT drink_id FROM drinks WHERE name = 'Spicy Fifty'), (SELECT ingredient_id FROM ingredients WHERE name = 'Vodka Vanilla'), '1 1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Spicy Fifty'), (SELECT ingredient_id FROM ingredients WHERE name = 'Elderflower Cordial'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Spicy Fifty'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '1/2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Spicy Fifty'), (SELECT ingredient_id FROM ingredients WHERE name = 'Monin Honey Syrup'), '1/3', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Spicy Fifty'), (SELECT ingredient_id FROM ingredients WHERE name = 'Thin Slices Red Chili Pepper'), '2', 'pcs'),
((SELECT drink_id FROM drinks WHERE name = 'Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'White Cuban Ron'), '2', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Lime Juice'), '3/4', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Daiquiri'), (SELECT ingredient_id FROM ingredients WHERE name = 'Superfine Sugar'), '2', 'bar spoons'),
((SELECT drink_id FROM drinks WHERE name = 'Alexander'), (SELECT ingredient_id FROM ingredients WHERE name = 'Cognac'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Alexander'), (SELECT ingredient_id FROM ingredients WHERE name = 'Crème de Cacao'), '1', 'oz'),
((SELECT drink_id FROM drinks WHERE name = 'Alexander'), (SELECT ingredient_id FROM ingredients WHERE name = 'Fresh Cream'), '1', 'oz');

