-- UPDATE statements to add garnishes to existing drinks
-- Generated from cocktails_data (1).csv

UPDATE drinks SET garnish = 'orange zest and maraschino cherry.' WHERE LOWER(name) = LOWER('Vieux Carré');
UPDATE drinks SET garnish = 'Celery, lemon wedge (Optional).' WHERE LOWER(name) = LOWER('Bloody Mary');
UPDATE drinks SET garnish = 'blackberries and optionally a lemon slice as well.' WHERE LOWER(name) = LOWER('Russian Spring Punch');
UPDATE drinks SET garnish = 'a slice of orange.' WHERE LOWER(name) = LOWER('Spritz');
UPDATE drinks SET garnish = 'half orange slice and maraschino cherry, optionally use orange zest.' WHERE LOWER(name) = LOWER('Whiskey Sour');
UPDATE drinks SET garnish = 'half orange slice.' WHERE LOWER(name) = LOWER('Sex on the Beach');
UPDATE drinks SET garnish = 'lemon slice (Optional).' WHERE LOWER(name) = LOWER('Long Island Iced Tea');
UPDATE drinks SET garnish = 'Few dashes of Amargo bitters on top as an aromatic garnish.' WHERE LOWER(name) = LOWER('Pisco Sour');
UPDATE drinks SET garnish = 'lemon slice and maraschino cherry.' WHERE LOWER(name) = LOWER('John Collins');
UPDATE drinks SET garnish = 'a lime slice.' WHERE LOWER(name) = LOWER('Grand Margarita');
UPDATE drinks SET garnish = 'lemon or orange zest with cherry.' WHERE LOWER(name) = LOWER('New York Sour');
UPDATE drinks SET garnish = 'an orange zest and cherry.' WHERE LOWER(name) = LOWER('Sea Breeze');
UPDATE drinks SET garnish = 'mint sprig and a slice of pineapple.' WHERE LOWER(name) = LOWER('Missionary’s Downfall');
UPDATE drinks SET garnish = 'Lemon zest.' WHERE LOWER(name) = LOWER('Martinez');
UPDATE drinks SET garnish = 'a lime slice.' WHERE LOWER(name) = LOWER('Tommy’s Margarita');
UPDATE drinks SET garnish = 'a red chili pepper.' WHERE LOWER(name) = LOWER('Spicy Fifty');
UPDATE drinks SET garnish = 'a lime slice.' WHERE LOWER(name) = LOWER('Moscow Mule');
UPDATE drinks SET garnish = 'Squeeze oil from lemon peel onto the drink.' WHERE LOWER(name) = LOWER('French Martini');
UPDATE drinks SET garnish = 'lemon zest.' WHERE LOWER(name) = LOWER('Rusty Nail');
UPDATE drinks SET garnish = 'rind of one lemon spiral.' WHERE LOWER(name) = LOWER('Horse’s Neck');
UPDATE drinks SET garnish = 'lemon zest.' WHERE LOWER(name) = LOWER('Vesper');
UPDATE drinks SET garnish = 'Orange zest.' WHERE LOWER(name) = LOWER('Hanky Panky');
UPDATE drinks SET garnish = 'pineapple spear, mint leaves and lime peel.' WHERE LOWER(name) = LOWER('Mai-Tai');
UPDATE drinks SET garnish = 'Half salt rim (Optional).' WHERE LOWER(name) = LOWER('Margarita');
UPDATE drinks SET garnish = '3 coffee beans' WHERE LOWER(name) = LOWER('Espresso Martini');
UPDATE drinks SET garnish = 'orange zest and maraschino cherry.' WHERE LOWER(name) = LOWER('Champagne Cocktail');
UPDATE drinks SET garnish = 'sprigs of mint and slice of lime.' WHERE LOWER(name) = LOWER('Mojito');
UPDATE drinks SET garnish = 'a slice of lime.' WHERE LOWER(name) = LOWER('Paloma');
UPDATE drinks SET garnish = 'half orange slice and a lemon zest.' WHERE LOWER(name) = LOWER('Americano');
UPDATE drinks SET garnish = 'Fresh raspberries.' WHERE LOWER(name) = LOWER('Clover Club');
UPDATE drinks SET garnish = 'lemon slice, optional lemon zest.' WHERE LOWER(name) = LOWER('Gin Fizz');
UPDATE drinks SET garnish = 'mint leaves and grated nutmeg.' WHERE LOWER(name) = LOWER('Chartreuse Swizzle');
UPDATE drinks SET garnish = 'Optionally garnish with a lemon or orange zest.' WHERE LOWER(name) = LOWER('Bee’s Knees');
UPDATE drinks SET garnish = 'citruses and dehydrated pineapple slice.' WHERE LOWER(name) = LOWER('IBA Tiki');
UPDATE drinks SET garnish = 'lemon zest.' WHERE LOWER(name) = LOWER('Remember the Maine');
UPDATE drinks SET garnish = 'a orange zest, optionally a lemon zest.' WHERE LOWER(name) = LOWER('Boulevardier');
UPDATE drinks SET garnish = 'Sprinkle with fresh ground nutmeg.' WHERE LOWER(name) = LOWER('Porto Flip');
UPDATE drinks SET garnish = 'lime wedge.' WHERE LOWER(name) = LOWER('Cuba Libre');
UPDATE drinks SET garnish = 'an orange wedge.' WHERE LOWER(name) = LOWER('Garibaldi');
UPDATE drinks SET garnish = 'a pineapple wedge.' WHERE LOWER(name) = LOWER('Jungle Bird');
UPDATE drinks SET garnish = 'a slice of orange.' WHERE LOWER(name) = LOWER('Tipperary');
UPDATE drinks SET garnish = 'Sprinkle fresh ground nutmeg on top.' WHERE LOWER(name) = LOWER('Alexander');
UPDATE drinks SET garnish = 'orange slice or zest, and a cocktail cherry.' WHERE LOWER(name) = LOWER('Old Fashioned');
UPDATE drinks SET garnish = 'a lemon zest and a maraschino cherry.' WHERE LOWER(name) = LOWER('Casino');
UPDATE drinks SET garnish = 'a lime wedge.' WHERE LOWER(name) = LOWER('Canchanchara');
UPDATE drinks SET garnish = 'mint springs.' WHERE LOWER(name) = LOWER('Old Cuban');
UPDATE drinks SET garnish = 'optionally with a lemon slice and blackberries.' WHERE LOWER(name) = LOWER('Bramble');
UPDATE drinks SET garnish = 'lemon twist.' WHERE LOWER(name) = LOWER('Cosmopolitan');
UPDATE drinks SET garnish = 'cherry and lemon zest.' WHERE LOWER(name) = LOWER('Tuxedo');
UPDATE drinks SET garnish = 'mint spring and optionally an orange slice as well.' WHERE LOWER(name) = LOWER('Suffering Bastard');
UPDATE drinks SET garnish = 'a mint sprig.' WHERE LOWER(name) = LOWER('Mint Julep');
UPDATE drinks SET garnish = 'lemon zest.' WHERE LOWER(name) = LOWER('Sazerac');
UPDATE drinks SET garnish = 'half orange slice or an orange zest.' WHERE LOWER(name) = LOWER('Tequila Sunrise');
UPDATE drinks SET garnish = 'orange zest.' WHERE LOWER(name) = LOWER('Planters Punch');
UPDATE drinks SET garnish = 'three cherries and a rectangular chunk of pineapple.' WHERE LOWER(name) = LOWER('Three Dots and a Dash');
UPDATE drinks SET garnish = 'Optional Maraschino Cherry.' WHERE LOWER(name) = LOWER('Aviation');
UPDATE drinks SET garnish = 'mint leaves.' WHERE LOWER(name) = LOWER('Zombie');
UPDATE drinks SET garnish = 'a orange twist.' WHERE LOWER(name) = LOWER('Rabo de Galo');
UPDATE drinks SET garnish = 'Squeeze oil from lemon peel onto the drink, or garnish with a green olives if requested.' WHERE LOWER(name) = LOWER('Dry Martini');
UPDATE drinks SET garnish = 'a lemon zest.' WHERE LOWER(name) = LOWER('Cardinale');
UPDATE drinks SET garnish = 'passion fruit cup and sugar.' WHERE LOWER(name) = LOWER('Porn Star Martini');
UPDATE drinks SET garnish = 'half orange slice.' WHERE LOWER(name) = LOWER('Negroni');
UPDATE drinks SET garnish = 'Rub a slice of orange (or lemon) around the rim of the glass and dip it in pulverized white sugar, so that the sugar will adhere to the edge of the glass. Carefully curling place the orange/lemon peel around the inside of the glass.' WHERE LOWER(name) = LOWER('Brandy Crusta');
UPDATE drinks SET garnish = 'fresh berries, ¼ wheel each orange and lemon. Serve with straws.' WHERE LOWER(name) = LOWER('Sherry Cobbler');
UPDATE drinks SET garnish = 'cocktail cherry.' WHERE LOWER(name) = LOWER('Manhattan');
UPDATE drinks SET garnish = 'orange twist (optional).' WHERE LOWER(name) = LOWER('Mimosa');
UPDATE drinks SET garnish = 'lemon zest and white grapes.' WHERE LOWER(name) = LOWER('Ve.N.To');
UPDATE drinks SET garnish = 'candied ginger slices.' WHERE LOWER(name) = LOWER('Penicillin');
UPDATE drinks SET garnish = 'a lime wedge or slice.' WHERE LOWER(name) = LOWER('Dark ‘N’ Stormy');
UPDATE drinks SET garnish = 'pineapple and maraschino cherry.' WHERE LOWER(name) = LOWER('Singapore Sling');
UPDATE drinks SET garnish = 'mint springs.' WHERE LOWER(name) = LOWER('South Side');
UPDATE drinks SET garnish = '1/2 passion fruit' WHERE LOWER(name) = LOWER('Don’s Special Daiquiri');
UPDATE drinks SET garnish = 'an orange zest.' WHERE LOWER(name) = LOWER('Corpse Reviver #2');
UPDATE drinks SET garnish = 'a slice of pineapple with a cocktail cherry.' WHERE LOWER(name) = LOWER('Pina Colada');
UPDATE drinks SET garnish = 'Optional mint leave.' WHERE LOWER(name) = LOWER('Stinger');

-- Total updates: 75
